export const roomData = [
  {
    room: 'One',
    roomName: 'Webentwicklung',
    roomId: 0,
    tables: {
      column: 2,
      tableData: [
        [
          {
            room: 'BJR',
            date: new Date(),
            position: 'horizontal',
            seat: '1',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '2',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '3',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '4',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '5',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '6',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '7',
            morning: false,
            afternoon: false,
          },
        ],
        [
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '8',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '9',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '4',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '10',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '11',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '12',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '13',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '14',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '15',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '16',
            morning: false,
            afternoon: false,
          },
        ],
      ],
    },
  },
  {
    room: 'Two',
    roomName: 'bb',
    roomId: 1,
    tables: {
      column: 1,
      tableData: [
        [
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '1',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '2',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '3',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '4',
            morning: false,
            afternoon: false,
          },
        ],
      ],
    },
  },
  {
    room: 'Three',
    roomName: 'Automotiv',
    roomId: 2,
    tables: {
      column: 1,
      tableData: [
        [
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '1',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '2',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '3',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '4',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '5',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '6',
            morning: false,
            afternoon: false,
          },
        ],
      ],
    },
  },
  {
    room: 'Four',
    roomName: 'ITC',
    roomId: 3,
    tables: {
      column: 1,
      tableData: [
        [
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '1',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '2',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '3',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '4',
            morning: false,
            afternoon: false,
          },
        ],
      ],
    },
  },

  {
    room: 'Five',
    roomName: 'Buchhaltung',
    roomId: 4,
    tables: {
      column: 2,
      tableData: [
        [
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '1',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '2',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '3',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '4',
            morning: false,
            afternoon: false,
          },
        ],
        [
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '5',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '6',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '7',
            morning: false,
            afternoon: false,
          },
          {
            room: 'BJR',
            date: new Date(),
            position: 'vertical',
            seat: '8',
            morning: false,
            afternoon: false,
          },
        ],
      ],
    },
  },
];
